[package]
name = "nightcycle/path-util"
description = "A package!"
version = "1.0.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]
